[[ordermanager_lib]]
arch = "x86_64"
git-tree-sha1 = "0e9f08cba0d04011952657b0293c23eed9e50ea8"
os = "windows"

    [[ordermanager_lib.download]]
    sha256 = "68af0d7f6804087c10ff1b25d22eb67500740cd31f825d4b5d06a17165400842"
    url = "https://github.com/linanisyugioh/OrderManager.jl/releases/download/V0.1.4/ordermanager_windows_x64.tar.gz"
[[ordermanager_lib]]
arch = "x86_64"
git-tree-sha1 = "a8616a51aec239e8c6937b0bc0493b5d615017ba"
libc = "glibc"
os = "linux"

    [[ordermanager_lib.download]]
    sha256 = "1eb5eb8300682b431311a832aee099b3aa015c89e6b90d29502717bdffb6ee34"
    url = "https://github.com/linanisyugioh/OrderManager.jl/releases/download/V0.1.4/ordermanager_linux_x64.tar.gz"
