[[ordermanager_lib]]
arch = "x86_64"
git-tree-sha1 = "a5f3eaf4b31459185695a2f1cb5d0601f48672dd"
os = "windows"

    [[ordermanager_lib.download]]
    sha256 = "338d38521b364547fb6ffdf98854a0d9c7e80a075477eba94ef3036affab1abc"
    url = "https://github.com/linanisyugioh/OrderManager.jl/releases/download/V0.1.17/ordermanager_windows_x64.tar.gz"
[[ordermanager_lib]]
arch = "x86_64"
git-tree-sha1 = "4eb5c35d83166bbdabcbab70a6e9756b8882ba00"
libc = "glibc"
os = "linux"

    [[ordermanager_lib.download]]
    sha256 = "ef049b1d77aa6ab563b502aaa5ff3817020723a2b66b6bdaca86b2ead79a434d"
    url = "https://github.com/linanisyugioh/OrderManager.jl/releases/download/V0.1.17/ordermanager_linux_x64.tar.gz"
